# Generated by Django 4.0.8 on 2022-11-06 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_app', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BetaTester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('score', models.IntegerField()),
                ('score_bug', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Report_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='report.betatester')),
                ('id_bug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='report.bug')),
                ('id_game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='report.application')),
            ],
        ),
    ]
