# Generated by Django 4.0.8 on 2022-10-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bt', models.IntegerField()),
                ('pseudo_bt', models.CharField(max_length=50)),
                ('id_game', models.IntegerField()),
                ('bug_type', models.CharField(max_length=50)),
            ],
        ),
    ]
